# nginx proxy address - http://172.17.0.1:8082

name: stirling-pdf
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    pull_policy: always
    container_name: stirling-pdf-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - stirling-pdf
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8082:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      DOCKER_ENABLE_SECURITY: "true"
      SECURITY_ENABLELOGIN: "true"
      SECURITY_INITIALLOGIN_USERNAME: ${APP_ADMIN_USER:-admin}
      SECURITY_INITIALLOGIN_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      DISABLE_ADDITIONAL_FEATURES: "false"
      CONTAINER_NAME: stirling-pdf-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/data/stirling-pdf:/usr/share/tessdata
      - ./volumes/config/stirling-pdf:/configs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://stirling-pdf-app:8080'
      - 'cloudflare.hostname=stirling-pdf.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.stirling-pdf-app.entrypoints=http'
      - 'traefik.http.routers.stirling-pdf-app-secure.tls=true'
      - 'traefik.http.routers.stirling-pdf-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.stirling-pdf-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.stirling-pdf-app.middlewares=stirling-pdf-app-https-redirect'
      - 'traefik.http.routers.stirling-pdf-app-secure.entrypoints=https'
      - 'traefik.http.routers.stirling-pdf-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.stirling-pdf-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.stirling-pdf-app-secure.service=stirling-pdf-app'
      - 'traefik.http.services.stirling-pdf-app.loadbalancer.server.port=8080'

networks:
  stirling-pdf:
    name: stirling-pdf
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
