# nginx proxy address - http://172.17.0.1:8082

name: stirling-pdf
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    pull_policy: always
    container_name: stirling-pdf-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - stirling-pdf
    ports:
      - "172.17.0.1:8082:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      DOCKER_ENABLE_SECURITY: "true"
      SECURITY_ENABLELOGIN: "true"
      SECURITY_INITIALLOGIN_USERNAME: ${APP_ADMIN_USER:-admin}
      SECURITY_INITIALLOGIN_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
    volumes:
      - ./volumes/data/stirling-pdf:/usr/share/tessdata
      - ./volumes/config/stirling-pdf:/configs
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  stirling-pdf:
    name: stirling-pdf
    external: false
